### ISSUE TITLE
logo proporsal requests

### ISSUE THREAD

**Issue by LuigiBaute** [rubyjobsru/app#33]
hello I would like to collaborate with your project for free by providing a logo or renewing it if you already have one

**Comment by soulim** [comment]
@LuigiBaute thanks for the initiative. The project has already [a logo](https://github.com/rubyjobsru/app/blob/29bf80ea9f2927e739ba70e890237841fb1be118/app/assets/images/rubyjobs-logo.svg), but if you have something better to offer, I'm open for a discussion.
